-- erp schema (shop/ERP tables) in Databricks Unity Catalog
-- E-commerce/ERP system tables using Delta Lake format
-- Catalog: origin_simulator_jaffle_corp | Schema: erp

-- Set catalog metadata
ALTER CATALOG origin_simulator_jaffle_corp
SET TAGS (
  'origin_simulator_version' = '1.0.0',
  'purpose' = 'dbt Origin Simulator demo source system',
  'managed_by' = 'dbt-origin-simulator-ops'
);

COMMENT ON CATALOG origin_simulator_jaffle_corp IS 'Demo source system catalog for dbt Origin Simulator. This catalog contains synthetic e-commerce and marketing data generated by the dbt-origin-simulator-ops package. It includes two schemas: erp (transactional shop data) and crm (marketing/customer engagement data). The data simulates a realistic operational database with baseline state and incremental daily changes.';

-- Create erp schema
CREATE SCHEMA IF NOT EXISTS origin_simulator_jaffle_corp.erp;

COMMENT ON SCHEMA origin_simulator_jaffle_corp.erp IS 'Enterprise Resource Planning (ERP) schema containing transactional e-commerce data. This schema includes customer master data, product catalog, orders, order line items, and payment transactions. Tables use soft delete pattern with deleted_at timestamp.';

-- Customers table
CREATE TABLE IF NOT EXISTS origin_simulator_jaffle_corp.erp.customers (
    customer_id INTEGER NOT NULL COMMENT 'Unique customer identifier',
    first_name VARCHAR(50) COMMENT 'Customer first name',
    last_name VARCHAR(50) COMMENT 'Customer last name',
    email VARCHAR(100) COMMENT 'Customer email address',
    created_at TIMESTAMP NOT NULL COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP NOT NULL COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP COMMENT 'Soft delete timestamp (NULL = active, non-NULL = deleted)',
    CONSTRAINT pk_customers PRIMARY KEY (customer_id) NOT ENFORCED
) USING DELTA
COMMENT 'Customer master data table';

-- Products table
CREATE TABLE IF NOT EXISTS origin_simulator_jaffle_corp.erp.products (
    product_id INTEGER NOT NULL COMMENT 'Unique product identifier',
    name VARCHAR(100) COMMENT 'Product name',
    category VARCHAR(50) COMMENT 'Product category',
    price DECIMAL(10,2) COMMENT 'Product unit price',
    created_at TIMESTAMP NOT NULL COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP NOT NULL COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP COMMENT 'Soft delete timestamp (NULL = active, non-NULL = discontinued)',
    CONSTRAINT pk_products PRIMARY KEY (product_id) NOT ENFORCED
) USING DELTA
COMMENT 'Product catalog table';

-- Orders table
CREATE TABLE IF NOT EXISTS origin_simulator_jaffle_corp.erp.orders (
    order_id INTEGER NOT NULL COMMENT 'Unique order identifier',
    customer_id INTEGER COMMENT 'Foreign key to customers table',
    order_date DATE COMMENT 'Order placement date',
    status VARCHAR(20) COMMENT 'Order status (pending, shipped, delivered, etc.)',
    created_at TIMESTAMP NOT NULL COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP NOT NULL COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP COMMENT 'Soft delete timestamp (NULL = active, non-NULL = cancelled)',
    CONSTRAINT pk_orders PRIMARY KEY (order_id) NOT ENFORCED,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES origin_simulator_jaffle_corp.erp.customers(customer_id) NOT ENFORCED
) USING DELTA
COMMENT 'Customer orders table';

-- Order items table
CREATE TABLE IF NOT EXISTS origin_simulator_jaffle_corp.erp.order_items (
    order_item_id INTEGER NOT NULL COMMENT 'Unique order line item identifier',
    order_id INTEGER COMMENT 'Foreign key to orders table',
    product_id INTEGER COMMENT 'Foreign key to products table',
    quantity INTEGER COMMENT 'Quantity ordered',
    unit_price DECIMAL(10,2) COMMENT 'Price per unit at time of order',
    created_at TIMESTAMP NOT NULL COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP NOT NULL COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP COMMENT 'Soft delete timestamp (rarely used)',
    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id) NOT ENFORCED,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES origin_simulator_jaffle_corp.erp.orders(order_id) NOT ENFORCED,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES origin_simulator_jaffle_corp.erp.products(product_id) NOT ENFORCED
) USING DELTA
COMMENT 'Order line items table';

-- Payments table
CREATE TABLE IF NOT EXISTS origin_simulator_jaffle_corp.erp.payments (
    payment_id INTEGER NOT NULL COMMENT 'Unique payment identifier',
    order_id INTEGER COMMENT 'Foreign key to orders table',
    payment_method VARCHAR(20) COMMENT 'Payment method (credit_card, bank_transfer, etc.)',
    amount DECIMAL(10,2) COMMENT 'Payment amount',
    created_at TIMESTAMP NOT NULL COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP NOT NULL COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP COMMENT 'Soft delete timestamp',
    CONSTRAINT pk_payments PRIMARY KEY (payment_id) NOT ENFORCED,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES origin_simulator_jaffle_corp.erp.orders(order_id) NOT ENFORCED
) USING DELTA
COMMENT 'Payment transactions table';
